### ISSUE TITLE
error when parsing vina scoring instruction.json

### ISSUE THREAD

**Issue by NiklasTR** [labdao/ganglia#33]

**Comment by NiklasTR** [comment]
ubuntu@ip-172-31-76-19:~/ganglia$ python3 process.py '{"container_id": "gnina/gnina:latest", "debug_logs": true, "short_args": {"v": "/home/ubuntu/casf-2016:/inputs"}, "cmd": "gnina -r /inputs/1a30/1a30_protein.pdb -l /inputs/1a30/1a30_ligand.sdf -o /inputs/1a30/1a30_scored_vina.sdf.gz --autobox_ligand /inputs/1a30/1a30_protein.pdb --cnn_scoring none --exhaustiveness 64 --score_only"}'
Traceback (most recent call last):
  File "process.py", line 65, in <module>
    main(instructions_json)
  File "process.py", line 52, in main
    docker_cmd = build_docker_cmd(instructions)
  File "process.py", line 43, in build_docker_cmd
    "docker"
KeyError: 'long_args'
